/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LoginRouteImport } from './app/login'
import { Route as IndexRouteImport } from './app/index'
import { Route as TemplatesIndexRouteImport } from './app/templates.index'
import { Route as SettingsIndexRouteImport } from './app/settings.index'
import { Route as KnowledgeIndexRouteImport } from './app/knowledge.index'
import { Route as BoardsIndexRouteImport } from './app/boards.index'
import { Route as SettingsAccountRouteImport } from './app/settings.account'
import { Route as KnowledgePublicIdRouteImport } from './app/knowledge.$publicId'
import { Route as CardsCardIdRouteImport } from './app/cards.$cardId'
import { Route as BoardsBoardIdRouteImport } from './app/boards.$boardId'
import { Route as ApiSplatRouteImport } from './app/api.$'
import { Route as TemplatesBoardIdIndexRouteImport } from './app/templates.$boardId.index'
import { Route as TemplatesBoardIdCardsCardIdRouteImport } from './app/templates.$boardId.cards.$cardId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgePublicIdRoute = KnowledgePublicIdRouteImport.update({
  id: '/knowledge/$publicId',
  path: '/knowledge/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesBoardIdIndexRoute = TemplatesBoardIdIndexRouteImport.update({
  id: '/templates/$boardId/',
  path: '/templates/$boardId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesBoardIdCardsCardIdRoute =
  TemplatesBoardIdCardsCardIdRouteImport.update({
    id: '/templates/$boardId/cards/$cardId',
    path: '/templates/$boardId/cards/$cardId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/knowledge/$publicId': typeof KnowledgePublicIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/boards/': typeof BoardsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/templates/$boardId/': typeof TemplatesBoardIdIndexRoute
  '/templates/$boardId/cards/$cardId': typeof TemplatesBoardIdCardsCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/knowledge/$publicId': typeof KnowledgePublicIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/boards': typeof BoardsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/templates/$boardId': typeof TemplatesBoardIdIndexRoute
  '/templates/$boardId/cards/$cardId': typeof TemplatesBoardIdCardsCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/knowledge/$publicId': typeof KnowledgePublicIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/boards/': typeof BoardsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/templates/$boardId/': typeof TemplatesBoardIdIndexRoute
  '/templates/$boardId/cards/$cardId': typeof TemplatesBoardIdCardsCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/$'
    | '/boards/$boardId'
    | '/cards/$cardId'
    | '/knowledge/$publicId'
    | '/settings/account'
    | '/boards/'
    | '/knowledge/'
    | '/settings/'
    | '/templates/'
    | '/templates/$boardId/'
    | '/templates/$boardId/cards/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/$'
    | '/boards/$boardId'
    | '/cards/$cardId'
    | '/knowledge/$publicId'
    | '/settings/account'
    | '/boards'
    | '/knowledge'
    | '/settings'
    | '/templates'
    | '/templates/$boardId'
    | '/templates/$boardId/cards/$cardId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/$'
    | '/boards/$boardId'
    | '/cards/$cardId'
    | '/knowledge/$publicId'
    | '/settings/account'
    | '/boards/'
    | '/knowledge/'
    | '/settings/'
    | '/templates/'
    | '/templates/$boardId/'
    | '/templates/$boardId/cards/$cardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
  KnowledgePublicIdRoute: typeof KnowledgePublicIdRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesBoardIdIndexRoute: typeof TemplatesBoardIdIndexRoute
  TemplatesBoardIdCardsCardIdRoute: typeof TemplatesBoardIdCardsCardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$publicId': {
      id: '/knowledge/$publicId'
      path: '/knowledge/$publicId'
      fullPath: '/knowledge/$publicId'
      preLoaderRoute: typeof KnowledgePublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$boardId/': {
      id: '/templates/$boardId/'
      path: '/templates/$boardId'
      fullPath: '/templates/$boardId/'
      preLoaderRoute: typeof TemplatesBoardIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$boardId/cards/$cardId': {
      id: '/templates/$boardId/cards/$cardId'
      path: '/templates/$boardId/cards/$cardId'
      fullPath: '/templates/$boardId/cards/$cardId'
      preLoaderRoute: typeof TemplatesBoardIdCardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  CardsCardIdRoute: CardsCardIdRoute,
  KnowledgePublicIdRoute: KnowledgePublicIdRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  BoardsIndexRoute: BoardsIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesBoardIdIndexRoute: TemplatesBoardIdIndexRoute,
  TemplatesBoardIdCardsCardIdRoute: TemplatesBoardIdCardsCardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
